---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	retriever(retriever)
	chess_analyst(chess_analyst)
	coach(coach)
	critic(critic)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	chess_analyst --> coach;
	coach -.-> __end__;
	coach -.-> critic;
	critic -.-> __end__;
	critic -.-> coach;
	retriever -.-> chess_analyst;
	retriever -.-> coach;
	supervisor -.-> chess_analyst;
	supervisor -.-> coach;
	supervisor -.-> retriever;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
