"""engine analysis

Revision ID: d89fbc8d8916
Revises: 417a1089ee0f
Create Date: 2026-07-26 16:52:51.171435

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d89fbc8d8916"
down_revision: str | Sequence[str] | None = "417a1089ee0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # `job_kind` gains 'engine_analysis'. Postgres has no reversible ADD VALUE, so this
    # widens it the standard way: rename, recreate with every member, recast the column,
    # drop the old type. Autogenerate does not diff enum *values* (only enum existence),
    # so this block is hand-written — it will not appear if this migration is
    # regenerated from a model diff.
    op.execute("ALTER TYPE job_kind RENAME TO job_kind_old")
    op.execute("CREATE TYPE job_kind AS ENUM ('pgn_import', 'engine_analysis')")
    op.execute("ALTER TABLE jobs ALTER COLUMN kind TYPE job_kind USING kind::text::job_kind")
    op.execute("DROP TYPE job_kind_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_analysis",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("analysis_version", sa.String(length=64), nullable=False),
        sa.Column("engine_depth", sa.Integer(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_game_analysis_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_analysis")),
    )
    op.create_index(op.f("ix_game_analysis_game_id"), "game_analysis", ["game_id"], unique=False)
    op.create_table(
        "move_evaluations",
        sa.Column("game_analysis_id", sa.UUID(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        sa.Column("eval_cp", sa.Integer(), nullable=True),
        sa.Column("mate_in", sa.Integer(), nullable=True),
        sa.Column("best_move_uci", sa.String(length=8), nullable=True),
        sa.Column("pv", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("best", "good", "inaccuracy", "mistake", "blunder", name="move_classification"),
            nullable=False,
        ),
        sa.Column("eval_swing_cp", sa.Integer(), nullable=False),
        sa.Column("is_critical_moment", sa.Boolean(), nullable=False),
        sa.Column("deep_analyzed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_analysis_id"],
            ["game_analysis.id"],
            name=op.f("fk_move_evaluations_game_analysis_id_game_analysis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("game_analysis_id", "ply", name="pk_move_evaluations"),
    )
    op.add_column("jobs", sa.Column("game_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_jobs_game_id"), "jobs", ["game_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_jobs_game_id_games"), "jobs", "games", ["game_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_jobs_game_id_games"), "jobs", type_="foreignkey")
    op.drop_index(op.f("ix_jobs_game_id"), table_name="jobs")
    op.drop_column("jobs", "game_id")
    op.drop_table("move_evaluations")
    op.drop_index(op.f("ix_game_analysis_game_id"), table_name="game_analysis")
    op.drop_table("game_analysis")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS move_classification")

    # Narrowing job_kind back to just 'pgn_import'. Fails if any row still has
    # kind='engine_analysis' — an inherent limitation of removing an enum value that's
    # in use, not something this migration can paper over. Fine for the clean-database
    # upgrade/downgrade/repeat cycle this project's test suite exercises.
    op.execute("ALTER TYPE job_kind RENAME TO job_kind_old")
    op.execute("CREATE TYPE job_kind AS ENUM ('pgn_import')")
    op.execute("ALTER TABLE jobs ALTER COLUMN kind TYPE job_kind USING kind::text::job_kind")
    op.execute("DROP TYPE job_kind_old")
