"""persona reports and llm usage

Revision ID: 25cd48a6006e
Revises: cee0b9f61b38
Create Date: 2026-07-28 00:16:40.305807

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25cd48a6006e"
down_revision: str | Sequence[str] | None = "cee0b9f61b38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage_daily",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("tokens_used", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_llm_usage_daily")),
    )
    op.create_table(
        "game_reports",
        sa.Column("game_id", sa.UUID(), nullable=False),
        # create_type=False: `persona` already exists, created by profiles.default_persona
        # in the identity migration — see the pattern-detection migration's game_color
        # comment for why postgresql.ENUM (not plain sa.Enum) is what makes the flag
        # actually take effect.
        sa.Column(
            "persona",
            postgresql.ENUM("self_learner", "coach", "kid", name="persona", create_type=False),
            nullable=False,
        ),
        sa.Column("source", sa.Enum("llm", "fallback", name="report_source"), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("analysis_version", sa.String(length=64), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fact_ids_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grounded", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_game_reports_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_reports")),
    )
    op.create_index(op.f("ix_game_reports_game_id"), "game_reports", ["game_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_reports_game_id"), table_name="game_reports")
    op.drop_table("game_reports")
    op.drop_table("llm_usage_daily")
    # ### end Alembic commands ###

    # persona is *not* dropped here: it was created by an earlier migration and
    # profiles.default_persona still depends on it (create_type=False above reflects
    # that it is shared, not owned) — same pattern as the pattern-detection migration's
    # game_color cleanup note.
    op.execute("DROP TYPE IF EXISTS report_source")
