"""knowledge corpus and retrieval

Revision ID: 578b7f6dc99b
Revises: af81c80410fa
Create Date: 2026-07-27 08:05:28.879131

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "578b7f6dc99b"
down_revision: str | Sequence[str] | None = "af81c80410fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The extension itself ships in the pgvector/pgvector:pg17 image (docker-compose.yml,
    # Phase 5), but must still be enabled per-database — first table that needs it, here.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "knowledge_documents",
        sa.Column(
            "bucket",
            sa.Enum("rules", "openings", "tactics", "strategy", name="knowledge_bucket"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("licence", sa.String(length=255), nullable=False),
        sa.Column("retrieved_at", sa.Date(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
        sa.UniqueConstraint("content_hash", name="uq_knowledge_documents_content_hash"),
    )
    op.create_index(
        op.f("ix_knowledge_documents_bucket"), "knowledge_documents", ["bucket"], unique=False
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        # postgresql.ENUM(create_type=False): `knowledge_bucket` already exists (created
        # by knowledge_documents.bucket above). Plain sa.Enum(create_type=False) does NOT
        # work here — the flag only takes effect on the dialect-specific postgresql.ENUM
        # class; sa.Enum silently drops it, which still issues a redundant CREATE TYPE
        # and fails with DuplicateObject. Same fix as game_color in the Phase 6 migration.
        sa.Column(
            "bucket",
            postgresql.ENUM(
                "rules",
                "openings",
                "tactics",
                "strategy",
                name="knowledge_bucket",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_chunks_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_knowledge_chunks_document_chunk_index"
        ),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_bucket"), "knowledge_chunks", ["bucket"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "analysis_knowledge_chunks",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_analysis_knowledge_chunks_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_analysis_knowledge_chunks_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_knowledge_chunks")),
    )
    op.create_index(
        op.f("ix_analysis_knowledge_chunks_game_id"),
        "analysis_knowledge_chunks",
        ["game_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_knowledge_chunks_profile_id"),
        "analysis_knowledge_chunks",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analysis_knowledge_chunks_profile_id"), table_name="analysis_knowledge_chunks"
    )
    op.drop_index(
        op.f("ix_analysis_knowledge_chunks_game_id"), table_name="analysis_knowledge_chunks"
    )
    op.drop_table("analysis_knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_document_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_bucket"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_documents_bucket"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    # ### end Alembic commands ###

    # Dropping a table does not drop the enum types its columns used — same pattern as
    # the Phase 6 migration's motif_type/strategic_theme_type cleanup. knowledge_bucket
    # is fully owned by this migration (unlike game_color, which predates it and is
    # never dropped), so it is dropped here, or a subsequent upgrade fails with
    # `type "knowledge_bucket" already exists`. The `vector` extension is left installed
    # deliberately — extensions are not per-migration-owned the way a type introduced
    # here is, and DROP EXTENSION risks cascading into anything else that comes to use it.
    op.execute("DROP TYPE IF EXISTS knowledge_bucket")
