"""training recommendations

Revision ID: 54d6d03c0cb5
Revises: 014484b643d3
Create Date: 2026-07-28 23:07:02.861814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54d6d03c0cb5"
down_revision: str | Sequence[str] | None = "014484b643d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_recommendations",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        # create_type=False for both enums below: `persona` and `report_source` already
        # exist, created by the identity and persona-reports migrations respectively —
        # same reuse pattern the persona-reports migration itself documents.
        sa.Column(
            "persona",
            postgresql.ENUM("self_learner", "coach", "kid", name="persona", create_type=False),
            nullable=False,
        ),
        sa.Column("window_size", sa.Integer(), nullable=False),
        sa.Column("snapshot_version", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM("llm", "fallback", name="report_source", create_type=False),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fact_ids_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("themes_covered", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grounded", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_training_recommendations_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_recommendations")),
    )
    op.create_index(
        op.f("ix_training_recommendations_profile_id"),
        "training_recommendations",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_training_recommendations_profile_id"), table_name="training_recommendations"
    )
    op.drop_table("training_recommendations")
    # ### end Alembic commands ###

    # `persona` and `report_source` are *not* dropped here: both are owned by earlier
    # migrations and still have other dependents (`profiles.default_persona`,
    # `game_reports.source`) — same pattern the persona-reports migration documents for
    # its own downgrade.
