"""identity baseline

Revision ID: 8846d28be571
Revises:
Create Date: 2026-07-26 09:41:48.920886

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8846d28be571"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "audit_events",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "user_login",
                "identity_linked",
                "profile_created",
                "profile_viewed",
                "relationship_granted",
                "relationship_revoked",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("subject_type", sa.String(length=64), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("self", "child", "student", "opponent", "shared", name="profile_kind"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "default_persona",
            sa.Enum("self_learner", "coach", "kid", name="persona"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_profiles_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_index(op.f("ix_profiles_owner_user_id"), "profiles", ["owner_user_id"], unique=False)
    op.create_table(
        "user_identities",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Enum("lichess", "chesscom", name="auth_provider"), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_username", sa.String(length=255), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identities")),
        sa.UniqueConstraint(
            "provider", "provider_user_id", name="uq_user_identities_provider_subject"
        ),
    )
    op.create_index(
        op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
    )
    op.create_table(
        "profile_relationships",
        sa.Column("viewer_user_id", sa.UUID(), nullable=False),
        sa.Column("subject_profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "coach", "parent", "viewer", "student", name="relationship_role"),
            nullable=False,
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subject_profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_relationships_subject_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["users.id"],
            name=op.f("fk_profile_relationships_viewer_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_relationships")),
        sa.UniqueConstraint(
            "viewer_user_id", "subject_profile_id", "role", name="uq_profile_relationships_grant"
        ),
    )
    op.create_index(
        op.f("ix_profile_relationships_subject_profile_id"),
        "profile_relationships",
        ["subject_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_relationships_viewer_user_id"),
        "profile_relationships",
        ["viewer_user_id"],
        unique=False,
    )
    op.create_table(
        "profile_sources",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "source", sa.Enum("lichess", "chesscom", "upload", name="game_source"), nullable=False
        ),
        sa.Column("source_username", sa.String(length=255), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_sources_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_sources")),
        sa.UniqueConstraint(
            "profile_id", "source", "source_username", name="uq_profile_sources_link"
        ),
    )
    op.create_index(
        op.f("ix_profile_sources_profile_id"), "profile_sources", ["profile_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_sources_profile_id"), table_name="profile_sources")
    op.drop_table("profile_sources")
    op.drop_index(
        op.f("ix_profile_relationships_viewer_user_id"), table_name="profile_relationships"
    )
    op.drop_index(
        op.f("ix_profile_relationships_subject_profile_id"), table_name="profile_relationships"
    )
    op.drop_table("profile_relationships")
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_table("user_identities")
    op.drop_index(op.f("ix_profiles_owner_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    # ### end Alembic commands ###
    # Alembic creates these enum types implicitly via create_table, but drop_table does
    # not remove them. Without these explicit drops the downgrade leaves the types
    # behind, and re-running the upgrade fails with "type ... already exists" — i.e. the
    # migration would not actually be reversible.
    for enum_name in (
        "audit_action",
        "auth_provider",
        "game_source",
        "persona",
        "profile_kind",
        "relationship_role",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
