"""best move san on move evaluations

Revision ID: d4413c217998
Revises: bdb59298c771
Create Date: 2026-07-29 18:38:50.256556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4413c217998'
down_revision: Union[str, Sequence[str], None] = 'bdb59298c771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_evaluations', sa.Column('best_move_san', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_evaluations', 'best_move_san')
    # ### end Alembic commands ###
