"""mate swing flag on move evaluations

Revision ID: bdb59298c771
Revises: 54d6d03c0cb5
Create Date: 2026-07-29 17:14:02.747297

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdb59298c771"
down_revision: str | Sequence[str] | None = "54d6d03c0cb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default lands the column as False for the ADD COLUMN itself (required since
    # existing rows must get some value); the UPDATE right after then reconstructs the
    # real flag for existing rows from data already on the table — each row's own
    # mate_in is the eval *before* that move (see MoveEvaluation's docstring), and the
    # next ply's mate_in (same game_analysis_id, ply + 1) is the eval *after* it, so both
    # sides of every existing swing are still recoverable without a full re-analysis.
    # (The very last ply of a game has no "after" row at all, since positions has N+1
    # entries for N stored plies — an unrecoverable, extremely rare edge case: the final
    # move of the game itself would have to walk into an engine-evaluated mate score.)
    op.add_column(
        "move_evaluations",
        sa.Column("mate_swing", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.execute(
        """
        UPDATE move_evaluations AS me
        SET mate_swing = TRUE
        WHERE me.mate_in IS NOT NULL
           OR EXISTS (
               SELECT 1 FROM move_evaluations AS nxt
               WHERE nxt.game_analysis_id = me.game_analysis_id
                 AND nxt.ply = me.ply + 1
                 AND nxt.mate_in IS NOT NULL
           )
        """
    )
    op.alter_column("move_evaluations", "mate_swing", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("move_evaluations", "mate_swing")
    # ### end Alembic commands ###
