"""chat threads

Revision ID: 28de2d593529
Revises: 25cd48a6006e
Create Date: 2026-07-28 08:14:30.057731

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28de2d593529"
down_revision: str | Sequence[str] | None = "25cd48a6006e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_threads",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("active_game_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_game_id"],
            ["games.id"],
            name=op.f("fk_chat_threads_active_game_id_games"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_chat_threads_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_threads")),
    )
    op.create_index(
        op.f("ix_chat_threads_active_game_id"), "chat_threads", ["active_game_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_threads_profile_id"), "chat_threads", ["profile_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_threads_profile_id"), table_name="chat_threads")
    op.drop_index(op.f("ix_chat_threads_active_game_id"), table_name="chat_threads")
    op.drop_table("chat_threads")
    # ### end Alembic commands ###
