"""canonical game moves

Revision ID: 417a1089ee0f
Revises: 4c9a072f9b6b
Create Date: 2026-07-26 15:08:13.436534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "417a1089ee0f"
down_revision: str | Sequence[str] | None = "4c9a072f9b6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_moves",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        sa.Column("san", sa.String(length=16), nullable=False),
        sa.Column("uci", sa.String(length=8), nullable=False),
        sa.Column("fen_before", sa.String(length=100), nullable=False),
        sa.Column("fen_after", sa.String(length=100), nullable=False),
        sa.Column("epd_after", sa.String(length=90), nullable=False),
        sa.Column("clock_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_game_moves_game_id_games"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("game_id", "ply", name="pk_game_moves"),
    )
    op.create_index(op.f("ix_game_moves_epd_after"), "game_moves", ["epd_after"], unique=False)
    op.add_column("games", sa.Column("canonicalized_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "games", sa.Column("parse_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "parse_error")
    op.drop_column("games", "canonicalized_at")
    op.drop_index(op.f("ix_game_moves_epd_after"), table_name="game_moves")
    op.drop_table("game_moves")
    # ### end Alembic commands ###
