"""report_type discriminator on game_reports

Revision ID: b7c1a04ab97c
Revises: d4413c217998
Create Date: 2026-07-29 22:10:05.527600

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7c1a04ab97c"
down_revision: str | Sequence[str] | None = "d4413c217998"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows are all the (only) pre-Phase-16b shape — the findings-list report.
    op.add_column(
        "game_reports",
        sa.Column("report_type", sa.String(length=20), nullable=False, server_default="findings"),
    )
    op.alter_column("game_reports", "report_type", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_reports", "report_type")
    # ### end Alembic commands ###
