"""imports baseline

Revision ID: 4c9a072f9b6b
Revises: 8846d28be571
Create Date: 2026-07-26 13:17:10.248741

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c9a072f9b6b"
down_revision: str | Sequence[str] | None = "8846d28be571"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("kind", sa.Enum("pgn_import", name="job_kind"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "done", "failed", name="job_status"),
            nullable=False,
        ),
        sa.Column(
            "progress",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_jobs_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_jobs_profile_id"), "jobs", ["profile_id"], unique=False)
    op.create_table(
        "games",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            # `create_type=False`: this Postgres enum already exists — created by
            # identity_baseline for `profile_sources.source`. Without this, Alembic tries
            # to CREATE TYPE a second time and the upgrade fails with "already exists".
            "source",
            postgresql.ENUM("lichess", "chesscom", "upload", name="game_source", create_type=False),
            nullable=False,
        ),
        sa.Column("source_game_ref", sa.String(length=255), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("focus_color", sa.Enum("white", "black", name="game_color"), nullable=True),
        sa.Column("opponent_name", sa.String(length=255), nullable=True),
        sa.Column("time_control", sa.String(length=64), nullable=True),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_pgn_path", sa.String(length=500), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_games_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_games_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
        sa.UniqueConstraint("profile_id", "content_hash", name="uq_games_profile_content_hash"),
    )
    op.create_index(op.f("ix_games_job_id"), "games", ["job_id"], unique=False)
    op.create_index(op.f("ix_games_profile_id"), "games", ["profile_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_profile_id"), table_name="games")
    op.drop_index(op.f("ix_games_job_id"), table_name="games")
    op.drop_table("games")
    op.drop_index(op.f("ix_jobs_profile_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
    # Alembic creates Postgres enum types implicitly inside create_table but does not drop
    # them on drop_table — see Phase 2's identity_baseline migration for the same fix.
    # `game_source` is excluded: it was created by the identity_baseline migration and
    # dropping it here would break that migration's own downgrade.
    for enum_name in ("game_color", "job_kind", "job_status"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
