"""opening detection and pattern intelligence

Revision ID: af81c80410fa
Revises: d89fbc8d8916
Create Date: 2026-07-26 20:15:45.091990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af81c80410fa"
down_revision: str | Sequence[str] | None = "d89fbc8d8916"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_openings",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("eco", sa.String(length=3), nullable=False),
        sa.Column("opening_name", sa.String(length=255), nullable=False),
        sa.Column("epd", sa.String(length=90), nullable=False),
        sa.Column("matched_ply", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_game_openings_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_openings")),
        sa.UniqueConstraint("game_id", name="uq_game_openings_game_id"),
    )
    op.create_index(op.f("ix_game_openings_game_id"), "game_openings", ["game_id"], unique=False)
    op.create_table(
        "game_strategy_tags",
        sa.Column("game_analysis_id", sa.UUID(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        # postgresql.ENUM(create_type=False): `game_color` already exists (created by the
        # games table's own focus_color column). Plain sa.Enum(create_type=False) does
        # NOT work here — the flag only takes effect on the dialect-specific
        # postgresql.ENUM class; sa.Enum silently drops it, which still issues a
        # redundant CREATE TYPE and fails with DuplicateObject.
        sa.Column(
            "side",
            postgresql.ENUM("white", "black", name="game_color", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "theme",
            sa.Enum(
                "weak_king_safety",
                "pawn_structure_damage",
                "passed_pawn_creation",
                "piece_activity_imbalance",
                "bad_bishop",
                "open_file_control",
                "centre_control",
                "space_advantage",
                "development_lag",
                "time_trouble_collapse",
                name="strategic_theme_type",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_analysis_id"],
            ["game_analysis.id"],
            name=op.f("fk_game_strategy_tags_game_analysis_id_game_analysis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_strategy_tags")),
    )
    op.create_index(
        op.f("ix_game_strategy_tags_game_analysis_id"),
        "game_strategy_tags",
        ["game_analysis_id"],
        unique=False,
    )
    op.create_table(
        "game_tactics",
        sa.Column("game_analysis_id", sa.UUID(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        sa.Column(
            "side",
            postgresql.ENUM("white", "black", name="game_color", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "motif",
            sa.Enum(
                "fork",
                "pin",
                "skewer",
                "discovered_attack",
                "double_check",
                "back_rank_mate",
                "smothered_mate",
                "hanging_piece",
                "removing_the_defender",
                "x_ray",
                name="motif_type",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_analysis_id"],
            ["game_analysis.id"],
            name=op.f("fk_game_tactics_game_analysis_id_game_analysis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_tactics")),
    )
    op.create_index(
        op.f("ix_game_tactics_game_analysis_id"), "game_tactics", ["game_analysis_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_tactics_game_analysis_id"), table_name="game_tactics")
    op.drop_table("game_tactics")
    op.drop_index(op.f("ix_game_strategy_tags_game_analysis_id"), table_name="game_strategy_tags")
    op.drop_table("game_strategy_tags")
    op.drop_index(op.f("ix_game_openings_game_id"), table_name="game_openings")
    op.drop_table("game_openings")
    # ### end Alembic commands ###

    # dropping a table does not drop the enum types its columns used — same pattern as
    # the engine_analysis migration's move_classification cleanup. game_color is *not*
    # dropped here: it was created by an earlier migration and games.focus_color still
    # depends on it (create_type=False above reflects that it is shared, not owned).
    op.execute("DROP TYPE IF EXISTS motif_type")
    op.execute("DROP TYPE IF EXISTS strategic_theme_type")
