"""profile aggregate snapshots

Revision ID: cee0b9f61b38
Revises: 578b7f6dc99b
Create Date: 2026-07-27 21:36:07.484462

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cee0b9f61b38"
down_revision: str | Sequence[str] | None = "578b7f6dc99b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_aggregate_snapshots",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("window_size", sa.Integer(), nullable=False),
        sa.Column("games_included", sa.Integer(), nullable=False),
        sa.Column("sufficient_sample", sa.Boolean(), nullable=False),
        sa.Column("snapshot_version", sa.String(length=64), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_aggregate_snapshots_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_aggregate_snapshots")),
    )
    op.create_index(
        op.f("ix_profile_aggregate_snapshots_profile_id"),
        "profile_aggregate_snapshots",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_profile_aggregate_snapshots_profile_id"), table_name="profile_aggregate_snapshots"
    )
    op.drop_table("profile_aggregate_snapshots")
    # ### end Alembic commands ###
